### ISSUE TITLE
Job failing ; exception error

### ISSUE THREAD

**Issue by tobystic** [sangonzal/repository-insights-action#41]
Hello,

I have been using this workflow for about 2 years with no issues but the jobs suddenly stopped running in November'23. When I look at the error returned in the job, I see "Resource protected by organization SAML enforcement". 

What I have done so far:
1. I ensured the PAT was not expired and even generated a new one with extended validity date.
2. I followed the steps in [issue 2661](https://github.com/cli/cli/issues/2661) and [Github docs](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on) to ensure write access by re-authorizing access. This error no longer occurs but the job still fails and now the error below is the current error:  _**"{"message": "Must have push access to repository", "documentation_url": "https://docs.github.com/rest/metrics/traffic#get-page-views"}`**_

 
`Traceback (most recent call last):
  File "/main.py", line 57, in <module>
    main()
  File "/main.py", line 25, in main
    views_frame = repo_stats.get_views(views_path)
  File "/repostats.py", line 9, in get_views
    views = self.repo.get_views_traffic()
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/Repository.py", line [19](https://github.com/Azure/Azure-Network-Security/actions/runs/7398228726/job/20126949735#step:4:20)86, in get_views_traffic
    headers, data = self._requester.requestJsonAndCheck(
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/root/-x-v5uFv0/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 **{"message": "Must have push access to repository", "documentation_url": "https://docs.github.com/rest/metrics/traffic#get-page-views"}`**

**Comment by sangonzal** [comment]
Hi @tobystic, given that nothing has changed in the extension and that it suddenly stopped working, I suspect that that maybe it was change in the repositories/organizations access policies. Do you have push permissions to the repository? Does the PAT?
